env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'arrow-body-style': 'off',
  'linebreak-style': ['error', 'windows'],
  'react/jsx-indent': [2, 4],
  'indent': ["error", 4],
  'react/jsx-filename-extension': [1, { "extensions": [".js", ".jsx", ".tsx"] }],
  'react/function-component-definition': [2, { "namedComponents": "arrow-function" }],
  'react/prop-types': "off",
  'import/no-unresolved': "off",
  'import/extensions': "off",
  'object-curly-newline': "off",
  'no-continue': "off",
}
